[project]
name = "graphmorph"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.10"
dependencies = [
    "dotenv>=0.9.9",
    "httpx>=0.28.1",
    "langchain-anthropic>=0.3.22",
    "langchain-core>=0.3.80",
    "langgraph>=0.6.11",
]
